### ISSUE TITLE
Is it possible

### ISSUE THREAD

**Issue by AhrimanSefid** [f4rber/BruteMiner#8]
Is it possible to separate the programs? 
As I have the IP's and ports, I only want to burtforce.

**Comment by f4rber** [comment]
python3 main.py -m 5

**Comment by AhrimanSefid** [comment]
not work.
very try.

**Comment by AhrimanSefid** [comment]
can add video

**Comment by AhrimanSefid** [comment]
![image](https://user-images.githubusercontent.com/1332246/148210024-fec0752a-c039-4abf-9463-aba28352eb14.png)
